version: '3.6'

services:
  app:
    container_name: react
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./app:/home
    ports:
      - "8080:8080"